language: php
os: linux
dist: focal
php:
  - 8.0
  - 7.4
  - 7.3
notifications:
  slack:
    secure: YHQZ+WgZKekFesNMc9FhjpT5uZvxtq73vCGomNWcBKrb4FkTu27uMpX5mDH9zSu7pNV32WM0B5lU9mhl34pJK8JFqLTeFKtbOXq/AB3BgRy47xXC82C7NPhlmSB9J950y6ruhiWXInOQYqNAptiNDFaHb3kbOTQiV2waXNKRIt8=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/213257627c4e40ffc03c
    on_success: change
    on_failure: always
    on_start: never
jobs:
  fast_finish: true
before_script:
  - composer install
script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.clover
