name: PHP Composer

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.3', '7.4', '8.0' ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, simplexml, libxml, curl, json
          coverage: pcov

      - name: PHP ${{ matrix.php }} - Validate composer.json and composer.lock
        run: composer validate

      - name: PHP ${{ matrix.php }} - Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: PHP ${{ matrix.php }} - Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install

      - name: PHP ${{ matrix.php }} - Run coverage test suite
        env:
          apiKey: ${{ secrets.STEAM_API_KEY }}
        run: composer run-script test

      - uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "${{ matrix.php }}: Tests failed."
          color: 'red'